### ISSUE TITLE
Metrics Server

### ISSUE THREAD

**Issue by hellouz818** [Scooter-2022/AI-HPA#10]
## 내용

기존 트래픽을 수집하는 HAProxy+프로메테우스를 사용하기로 하였는데, 트래픽 수집과 거의 비례하는 각 파드별 CPU 사용량을 수집하고자 변경
따라서 메트릭 서버를 이용하고자 함

## 작업 내용

- [x] 메트릭 서버 추가
- [x] 특정 deploy에 해당하는 Pod만 선별해올 수 있는 방법 모색
- [x] 파드 내에서 메트릭 서버에 API 요청 보내서 응답 받아오기

## 참고 사항
https://github.com/kubernetes-sigs/metrics-server

**Comment by bconfiden2** [comment]
[파드 내에서 쿠버네티스 API에 접근](https://kubernetes.io/ko/docs/tasks/run-application/access-api-from-pod/)
[Metrics API](https://kubernetes.io/docs/tasks/debug/debug-cluster/resource-metrics-pipeline/#metrics-api)
[python api call header](https://stackoverflow.com/questions/29931671/making-an-api-call-in-python-with-an-api-that-requires-a-bearer-token)

**Comment by bconfiden2** [comment]
메트릭 서버 yaml 파일 등등은 여기 브랜치로 진행하되
메트릭 서버에 API 요청 보내서 응답 받아오는 부분은 스케일러 역할이니 #9 쪽으로 커밋해줘!

**Comment by bconfiden2** [comment]
쿠버네티스 클러스터에 메트릭 서버가 없을 경우 생성할 수 있는 metrics-server.yaml 파일이랑,
파드 내부에서 API 요청을 보낼 수 있게끔 롤바인딩하는 rbac.yaml 파일 추가

[참고 - RBAC Deny](https://github.com/kubernetes-sigs/metrics-server/issues/40)
