### ISSUE TITLE
CI/CD apply

### ISSUE THREAD

**Issue by NayeonKeum** [Scooter-2022/AI-HPA#11]
## 내용

- CI/CD 적용을 위해서 작업용 branch 파기
- 작업용 브랜치에서 자유롭게 커밋하여 젠킨스로 빌드해가면서 테스트
- 핵심 내용들만 feat 브랜치에 커밋

**Comment by bconfiden2** [comment]
각자 젠킨스로 웹훅 보낼 레포 주소랑 브랜치명 알려줘! @NayeonKeum @hellouz818 @asd3638 

~나는 fork 떠가서~&nbsp;&nbsp;브랜치 새로 파서 진행할 예정이라, 나를 예로 들면
저장소 : https://github.com/Scooter-2022/AI-HPA.git/
브랜치 : ci/ksh
