### ISSUE TITLE
RBAC 설정으로 ServiceAccount 에 metrics api 권한 주기

### ISSUE THREAD

**Issue by bconfiden2** [Scooter-2022/AI-HPA#13]
## 내용

#10 에서 메트릭서버 올리고, 다른 파드들에서 내부 토큰이랑 인증서 가지고 https 요청 날려도 접근권한 이슈 403을 띄웠음

그래서 [rbac.yaml](https://github.com/Scooter-2022/AI-HPA/blob/feat/%2310/Collect/rbac.yaml) 내용처럼 클러스터롤이랑 바인딩 추가해서 default 라는 ServiceAccount로 default 네임스페이스에 생성된 파드들에 대해서는 메트릭서버로 요청 보내는 것은 확인했는데,

걱정되는 부분은 이 파드가 클러스터롤에 지정된 네임스페이스가 아니라 다른데 생성되는 경우나, 다른 ServiceAccount 를 지정하는 경우가 있기 때문에 근본적인 해결책이 아니라는 점?

만약 파드를 다른 네임스페이스에 띄울 경우 rbac.yaml 파일의 내용을 자동으로 변경할 수 있을지???

**Comment by hellouz818** [comment]
Web을 만든다면, 기본은 default로 설정해놓은 뒤, 사용자의 입력값에 의하여 네임스페이스 값을 수정할 수 있도록 하는 것은 어떨지?

(보통 헬름차트들도 기본적으로 default이고 사용자가 그에 맞게 파일을 수정하곤함)

**Comment by bconfiden2** [comment]
맞아 나도 웹에서 사용자의 ServiceAccount 랑 Namespace 값을 입력받는걸로 생각했음 ㅇㅇ
그러면 반환해주는 전체 yaml 파일 중에 해당하는 부분이 입력값에 맞게 변경되는 느낌?

**Comment by NayeonKeum** [comment]
이거 그냥 shell script로 환경변수 지정하면 될듯?
readme에다가 네임스페이스랑 서비스 이름같은거 입력 받아서 실행시킬 수 있도록

+ 자세한거 이슈#14에 댓글 달았음

**Comment by bconfiden2** [comment]
쉘스크립트 말고 헬름차트들 마냥 values.yaml 에다가 지정할 수는 없는건가?

**Comment by NayeonKeum** [comment]
헬름차트도 실행시킬 때 파라미터를 넣는 형식이라서 실행하는 걸 쉘스크립트로 만들어서 변수 넣으면 가능할듯!

**Comment by bconfiden2** [comment]
오키오키 그럼 일단 나중에 브랜치 하나 파서 진행하는걸로 하자
