### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by hellouz818** [Scooter-2022/AI-HPA#14]
## 내용

성능 비교 및 사용자용 커스텀 yaml 제공을 위한 Web 구현

## 참고 사항

전반적인 주요 기능 개발이 마무리 된 이후 성능비교(예측한 파드 수)를 시각화한 탭, 각자 사용환경에 맞는 yaml 파일을 다운로드 할 수 있는 간단한 Web UI를 만들어서 제공하는건 어떨지 논의하고 싶습니다.

**Comment by bconfiden2** [comment]
난 이거 좋을듯
모델 학습시킨다음 테스트 자동화해서 웹으로 볼 수 있으면 편하기도하고??

**Comment by NayeonKeum** [comment]
나는 굳이 없어도 될 것 같은게,, 우리가 web으로 사용자에게 성능 비교를 할 이유가 있나?
그 성능을 비교해서 더 좋은 걸 쓰자는 생각은 우리가 만든 PHPA가 성능이 더 떨어질 수 있다는 걸 전제하는거고
우리는 우리의 모델이 성능이 더 좋다는걸 증명하는게 과제니까,, 과제에서는 명시하는게 당연하지만 사용자가 그 차이를 알 필요는 없다고 생각해,,

그리고 사용환경에 맞는 yaml을 다운받기 위해 입력값을 넣으려고 굳이 web UI를 만드는 건 자원과 시간 낭비라고 생각해! 그냥 환경변수로 만들어 놓는 shell script를 readme로 명시해주면 되는거 아닌가?

하고 싶으면 마지막에 시간 남았을 때 하면 될 것 같음

**Comment by asd3638** [comment]
나도 굳이 싶어!

**Comment by bconfiden2** [comment]
모델 성능 전반적으로 잘 뽑히고 마지막에 여유 있으면 추가적으로 레포 파서 진행하는 것도 나쁘지 않고??

**Comment by bconfiden2** [comment]
개발 내용 명시할때는 #15 처럼 프로메테우스랑 그라파나 활용해서 써보는걸로 하자 그럼

**Comment by hellouz818** [comment]
좋은 논의였다... 나도 동의해! 그럼 이 이슈는 닫을게!
