### ISSUE TITLE
스케일러 모듈 - Go 라이브러리 사용하기

### ISSUE THREAD

**Issue by bconfiden2** [Scooter-2022/AI-HPA#17]
## 내용

현재 파이썬으로 apiserver 에 api 요청 보내고 있는 방식을, Go 에서 제공해주는 클라이언트 라이브러리를 활용하도록 수정하기

## 작업 내용

- [ ] Metrics API 호출 부분 변경
- [ ] Scale API 호출 부분 변경
- [ ] golang HTTP client

**Comment by hellouz818** [comment]
지금 1.0버전 말고 추후 버전에서 업그레이드 합니다..!!! 따흑!

**Comment by bconfiden2** [comment]
나태지옥에 가겠습니다
