### ISSUE TITLE
Prediction Model

### ISSUE THREAD

**Issue by bconfiden2** [Scooter-2022/AI-HPA#18]
## 내용

Predict 모듈 관련된 요구사항들 개발

## 작업 내용

- [x] 스케일러 모듈의 요청을 받아줄 http 서버
- [ ] 학습된 모델 predict 모듈에 삽입
- [ ] 입력값을 가지고 모델에 inference 하여 예측값을 반환해주는 코드(or 함수)

## 참고 사항
http 서버는 파이썬의 fastapi 를 사용할 예정

**Comment by NayeonKeum** [comment]
확인했슴니다!

**Comment by bconfiden2** [comment]
옙 http 서버는 제가 하겠슴다
