### ISSUE TITLE
사용자가 지정한 인터벌로 스케일링 진행

### ISSUE THREAD

**Issue by bconfiden2** [Scooter-2022/AI-HPA#24]
## 내용

현재는 코드에 고정적으로 10초 주기로 워크플로우가 반복되는데,
이를 사용자 지정값을 받아와서 적용하게끔 변경

## 작업 내용

- [x] 사용자 지정값 받아오기
- [x] Update.workflow.py 의 time.sleep() 부분 변경

**Comment by hellouz818** [comment]
그렇다면 파드 생성시 사용자가 환경변수 등으로 지정한 값을 받아오고, 만약 없다면 고정값 10으로 정해서 파이썬 코드를 고치면 될까?

assignee로 안되어있지만 지금 이 부분 하고 있어서 수정할 수 있으면 해보려구

**Comment by NayeonKeum** [comment]
넵 그러면 될 것 같아!

**Comment by NayeonKeum** [comment]
모델에도 time interval 적용하기 위해 재오픈
