### ISSUE TITLE
스케일러의 메트릭 수집 인터벌 vs 스케일링 인터벌

### ISSUE THREAD

**Issue by bconfiden2** [Scooter-2022/AI-HPA#25]
## 내용

스케일링은 1분마다 진행한다고 할 때,
스케일러가 메트릭을 수집하는 주기가 1분이라고 한다면 트래픽을 1분 단위로 모니터링하기 때문에
급작스러운 트래픽 변화를 감지하여 대응하지는 못할 것으로 보임

따라서 트래픽(=cpu사용량)을 좀 더 실제와 같이 수집하여 예측하기 위해 메트릭을 수집하는 주기를 다르게 가져가는 것은 어떨까??

예를 들어 스케일링은 1분 주기로 진행하더라도, 그동안에 메트릭들을 5초 단위로 수집함으로써
입력값 하나를 기존처럼 1차원이 아니라 12차원으로 넣어버리는거지!
12차원짜리 입력값들을 30개 모아서 인퍼런스하게끔!

**Comment by NayeonKeum** [comment]
괜찮은데 그렇게 해도 1분 단위로 모니터링을 하는 건 똑같지 않나? threshold를 넘었을 때 스케일링 되는 게 아니라 시간 단위에 의해 스케일링 되는거니까.. 30 -> 1 학습이나 360 -> 1 학습이나 양만 다르게 하면 돼서 바꾸는게 어렵지는 않을 것 같은데 의미는 똑같을 것 같아서

**Comment by bconfiden2** [comment]
```threshold를 넘었을 때 스케일링 되는 게 아니라 시간 단위에 의해 스케일링 되는거니까``` 이게 무슨 말인지 모르겠다..??

## T1, T2, ... , T30 까지의 값을 넣었을 때 T31 시점에서의 필요한 파드를 예측해야 함

### 이 때 각 T값들이 원래는 1분마다 **한번씩**만 측정된 값일 때 발생하는 문제
예를 들어 0초부터 60초까지 중에, 20~40초에는 트래픽이 확 튀었지만 그 이후로 다시 잠잠해질 경우, 60초 시점을 기준으로 측정되기 때문에 전반적인 흐름을 잡지 못함

### 메트릭 수집 주기를 짧게 해서 여러번 측정된 메트릭을 하나로 묶어서 보낼 경우
메트릭들이 계속 수집되기 때문에 실제 트래픽의 흐름을 최대한 반영시킬 수 있음
0초부터 60초 사이에 들어온 트래픽들을 예를 들어 5초 단위로 묶어서 각각의 T값을 다차원으로 구성하여 학습
학습할 때 T30 ~ T31 사이의 60초 동안의 트래픽들을 모두 처리할 수 있도록 하는 T31 의 파드 수 예측

<br>

라는 느낌???

**Comment by NayeonKeum** [comment]
흠.. 그러면 기준 초를 줄이고(ex. 60초 -> 20초) 각 구간에서 최댓값을 샘플링하는건 어때? 초별로 값만 수집되면 max로 샘플링할 수 있고, 초 단위는 지금은 1분으로 하고 있는데 줄일 수 있음

**Comment by bconfiden2** [comment]
그럼 스케일링 주기 자체가 너무 짧아지지 않을까 싶어서..

**Comment by NayeonKeum** [comment]
구간 유지, shape 유지하여 진행하기로 함
