### ISSUE TITLE
모델과 스케일러가 통신할 때 curr_pods 필요 없음

### ISSUE THREAD

**Issue by bconfiden2** [Scooter-2022/AI-HPA#26]
## 내용

현재 모델의 http 서버가 cpu사용량과 현재 파드 수를 받아오는데
인퍼런스 과정에서 굳이 필요 없을 것으로 판단

## 작업 내용

- [x] http 서버에서 curr_pod 제거
- [x] 스케일러 쪽에서 POST 요청을 보낼 때 전송하는 데이터 수정

**Comment by asd3638** [comment]
인퍼런스 과정에서 굳이 필요없다는게 무슨 말이야??

**Comment by bconfiden2** [comment]
저 API 명세가 예전에 합의됐던거라 그때 당시에는 필요했는데,
우리 프로젝트 계속 바뀌게 되면서 지금 상태에서는 불필요해서 빼달라는 뜻!
