### ISSUE TITLE
모델에 보내는 usage_data 수정

### ISSUE THREAD

**Issue by bconfiden2** [Scooter-2022/AI-HPA#27]
## 내용

현재는 진짜 cpu 사용량을 보내서, 모델 쪽에서 필요 파드 수로 변환하여 인퍼런스하는 방식으로 생각하고 짰음
그러나 모델 쪽에서 애초에 파드 수를 받기만 해서 바로 모델에 인퍼런스하는 방식으로 변경하였기 때문에,
스케일러 쪽에서 POST 요청을 보내기 전에 변환하는 추가 과정이 필요

## 작업 내용

- [x] 사용자가 지정한 cpu limit 가져오기
- [x] #29
- [x] cpu 사용량을 파드 수로 변환

**Comment by hellouz818** [comment]
사용자가 지정한 cpu limit 가져오기 
-> 이 내용을 나는 `kubectl top nodes`에서 실제 cpu 사용량과 그에따른 퍼센테이지가 나와서 100/현재 퍼센테이지로 나눈뒤에 cpu양을 곱해주는 방식으로 진행하려고 했는데 이게 사용자가 지정한 cpu limit 같진 않은데,,
```
NAME              CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
testpool-w-1hyo   74m          3%     1819Mi          23%    

라면 100/3 * 74m 라고 계산
 ```
 
아니면 yaml 파일에 명시한 resources에 limit으로 나타낸 값을 가져와야하는것일까?

kubectl describe nodes에서 나오는 cpu, limits와 
kubectl top nodes 에서 나오는 cpu의 값이 다르게 나타나는데 아직 이해가 잘 안되어서 조금 더 공부해봐야할것 같아! 🥲

**Comment by bconfiden2** [comment]
yaml에 명시한 리밋!!

**Comment by hellouz818** [comment]
yaml에 명시한 리밋을 가져올때 그 파드안에 컨테이너별로 리소스를 지정해준 값을 가져오는거잖아
궁금한 사항이 있는데 

1. 만약 그렇다면, yaml 안에 resources의 request나 limit을 지정을 안해준다면,,? 

2. 그리고 여기서도 파드의 이름을 알아야만 해당 파드의 컨테이너별 리밋값을 가져오는 걸까? 
ex)`kubectl get pod cpu-demo --output=yaml --namespace=cpu-example`[링크](https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/)
아니면, 그냥 디플로이로 생성된 파드들의 셀렉터로 필터를 해서 디플로이의 yaml에 작성한 리밋값을 가져오는걸까?
ex)`kubectl get pods --field-selector status.phase=Running`[링크](https://kubernetes.io/ko/docs/concepts/overview/working-with-objects/field-selectors/)

파드 이름으로 가져오려고 했다가 조금 헷갈려서 남겨봐

**Comment by bconfiden2** [comment]
1. 지정을 안해주는 경우 디폴트값을 설정해놓으면 될 것 같고....
2. https://kubernetes.io/docs/concepts/workloads/pods/downward-api/  이거 참고해봐!!

**Comment by hellouz818** [comment]
1. 리밋을 지정을 안하면 파드는 노드 안에 모든 사용량을 쓸 수 있어서 리밋을 정하는것을 권장하지만, 디폴트값은 안 정해져있다.. 이걸 어떻게 될 줄 알고 우리가 마음대로 설정하는게 맞을까?
2. 그럼 사용자에게 strict하게 작성을 강제하는게 맞을까?

**Comment by NayeonKeum** [comment]
그런데 deployment 별로 pod 수 받아오는 api는 없나? cpu 사용량 가져와서 변환해야하는 이유가 뭐지? 
그때 변환하는 이슈 때문에 pod 수로만 하자는 얘기를 했던 것 같아서..

**Comment by hellouz818** [comment]
파드 내부의 cpu사용량이 limit에 근접했을때, 새로운 추가 파드가 필요하다라고 인지하여서 추가 파드를 생성하는거기때문에 파드 내부의 cpu 사용량을 가져오는것은 필요한것 같아!

**Comment by hellouz818** [comment]
헷갈려서 혼자 정리하는 흐름도

1. 사용자가 scale하고 싶은 타겟의 cpu 사용량을 알아오기 (현재는 test-nginx-deployment라는 이름으로 테스트 중) 
1-1.  total_cpu_usage를 받아와서 수정
2. 리밋과 현재 사용량이 우리가 지정한 리밋비율(현재 80프로라고 지정)을 초과한다면 
2-1. `if 현재 사용량 / 리밋 > 80` 파드 수 증가..? -> 하지만 이것은 모델이 하는것 
그렇다면 정해진 비율을 넘는다면 무엇을 해야하는가? 
3. cpu사용량을 pod수로 변환하여 파드-> 여기가 애매

**Comment by hellouz818** [comment]
위에서 헷갈렸던 부분이 해결되어 다시 코멘트 남겨!

커밋은 기존에 모델에 들어가는 파드 수의 갯수가 30개 -> 10개로 조정하였고, 초기 실행시에 파드수가 더미데이터 1로 들어가있어서 모델에서 필요에 따라 더미 데이터 수정하면 될듯해! (#36)

그리고 모델의 예측 레플리카 수를 리스트에 담지 않고, 현재 cpu 실제 사용량에 기반하여 필요 파드 수로 변환한 값을 리스트에 담아 모델에 넘겼어!

유저가 지정한 cpu 리밋이 없다면 디폴트 250m로 지정해놓긴했는데,, downward-api 관련해서 수정할 수 있음 해볼게,,~
