### ISSUE TITLE
limit 대비 얼마까지 사용할 수 있을지 비율 정하기

### ISSUE THREAD

**Issue by hellouz818** [Scooter-2022/AI-HPA#29]
## 내용

비율은 어떠한 방식으로 정해야 괜찮을까요? 임의로 정하는지,,

**Comment by bconfiden2** [comment]
저번에 나연이랑 지혜랑 얘기했을 때는,
우리 목표는 트래픽을 다 처리할 수 있도록 미리 예측해서 스케일링해놓는 것이기 때문에
이론상 이 비율은 사실상 최대한 땡겨써도 문제가 없을 것이다...

이긴 했지만, @NayeonKeum 어떻게 생각해

**Comment by NayeonKeum** [comment]
옴마 지금 봐버렸네.. ㅇㅇ 주관적으로 상관없을듯!

**Comment by hellouz818** [comment]
그렇다면 CPU throttle과 같은 문제는 따로 생각해주지 않아도 괜찮은건가?

**Comment by bconfiden2** [comment]
여기서 말하는 쓰로틀은 무슨 뜻이야???

**Comment by hellouz818** [comment]
공유되는 메모리가 겹치면 우선순위가 낮은 Pod 또는 프로세스를 강제로 종료한다(아마 pod eviction)는 글을 봐서, CPU가 아닌 메모리랑 헷갈렸나봐 쏘리쏘리,,~

**Comment by hellouz818** [comment]
그렇담 limit 대비 80프로가 넘는다면 pod수를 늘리도록 퍼센티지를 지정해서 해볼게 조언 고마워~👍
