### ISSUE TITLE
모델 오버피팅 해결

### ISSUE THREAD

**Issue by NayeonKeum** [Scooter-2022/AI-HPA#37]
## 내용

없앤 줄 알았는데.. 아니었다..

## ISSUE 분류를 선택하세요

- [x] Fix

## 작업 내용

- [x] 모델 오버피팅 수정하여 모델 파일 업로드

**Comment by bconfiden2** [comment]
이거는 모델레포쪽 이슈 아냐?? 🤔

**Comment by NayeonKeum** [comment]
아 해결하고 나서 모델만 갈아끼운다는 이슈였어! 모델쪽은 따로 올려유~
