### ISSUE TITLE
메트릭 수집

### ISSUE THREAD

**Issue by asd3638** [Scooter-2022/AI-HPA#4]
## 내용

프로메테우스 설정
haproxy-exporter 설정

## 작업 내용

- [ ] 프로메테우스 설정
- [ ] haproxy-exporter 연결

**Comment by bconfiden2** [comment]
https://observability.thomasriley.co.uk/prometheus/configuring-prometheus/using-service-monitors/

~인그레스나 haproxy exporter 없이 할 수 있는 것 같기도 한데... 확인 부탁!~

>모니터링할 서비스의 kind 자체가 달라져야 하기 때문에 유연하게 붙을 수 없을 듯

**Comment by bconfiden2** [comment]
https://sysdig.com/blog/kubernetes-monitoring-prometheus/

여기 중간 부분에 있는, **How to monitor Kubernetes services with Prometheus exporters** 부분부터 참고

**Comment by hellouz818** [comment]
프로메테우스 대신 이런 방식으로 수정하려고 함!
Assignees가 확인되면, 해당 이슈는 close할 예정!

> Metrics Server #10

**Comment by bconfiden2** [comment]
확인했습니다
