### ISSUE TITLE
Predict pseudo code

### ISSUE THREAD

**Issue by NayeonKeum** [Scooter-2022/AI-HPA#5]
## 내용

예측 수도 코드 생성

## 작업 내용

- [x] 수도 코드 만들기
- [x] 도커 이미지 생성

## 참고 사항
- api 생성 이후 테스트 필요

**Comment by NayeonKeum** [comment]
이미지 내부에서는 socket 통신으로 model, pseudo, server 연결
- k8s에 이미지로 띄워서 ip 연결 및 api test 필요

**Comment by bconfiden2** [comment]
클라이언트쪽 코드는 스케일러에서 사용해야하니 #9 쪽에다가 커밋해주세요
해당 코드 바탕으로 수정해나가겠음

**Comment by NayeonKeum** [comment]
관련된 내용 #18 에서 이어서 하기로 함.
