### ISSUE TITLE
부하 테스트기

### ISSUE THREAD

**Issue by bconfiden2** [Scooter-2022/AI-HPA#6]
## 내용

오토스케일링 성능 테스트를 위한 부하 발생기 라이브러리 확인 및 테스트 코드

## 작업 내용

- [x] 라이브러리 선정 및 설치
- [x] 부하 발생시키기

## 참고 사항
https://www.containiq.com/post/kubernetes-load-testing

부하 발생기 라이브러리 : K6
[k6 공식 문서](https://k6.io/docs/) &nbsp;&nbsp; / &nbsp;&nbsp; [k6 깃헙](https://github.com/grafana/k6#running-k6)

**Comment by bconfiden2** [comment]
HPA, PHPA, AIHPA 비교하기
비교 내용을 시각적으로 확인할 수 있을지 - 프로메테우스?

**Comment by bconfiden2** [comment]
@hellouz818 @asd3638

**Comment by hellouz818** [comment]
Prometheus - Grafana를 사용하여 그래프로서 시각화

프로메테우스에서 디플로이별 파드 수를 가져오는 방식을
1. PromQL을 사용하여 전체 메트릭에서 선택적으로 쿼리를 날리는 방식
2. 파드 관련 custom한 exporter를 찾아 띄우는 방식

위의 두가지 방식을 시도해볼 예정

**Comment by bconfiden2** [comment]
테스트 자동화는 #15 시각화 쪽에서 같이 진행
